---
# A list of directories on the test host that fio jobs will be run against
fio_input_dirs:
- /tmptest

# Where to store the fio logs on the test host we're running fio on
fio_output_dir: /tmp/fio_tests

# This relates to a directory on the host running ansible. The fio results tarball
# will be fetched and stored in this location
fio_fetch_dir: /tmp/fio_tests

fio_job_time: 10m
fio_job_size: 30g
fio_iodepth: 64
fio_ramp_time: 3m

fio_jobs:
  8k:
    rw:
    - randread
    - randwrite
    runtime: "{{ fio_job_time }}"
    ramp_time: "{{ fio_ramp_time }}"
    size: "{{ fio_job_size }}"
    iodepth: "{{ fio_iodepth }}"
    stonewall:
  64k:
    rw:
    - randread
    - randwrite
    runtime: "{{ fio_job_time }}"
    ramp_time: "{{ fio_ramp_time }}"
    size: "{{ fio_job_size }}"
    iodepth: "{{ fio_iodepth }}"
    stonewall:
  1m:
    rw:
    - randread
    - randwrite
    runtime: "{{ fio_job_time }}"
    ramp_time: "{{ fio_ramp_time }}"
    size: "{{ fio_job_size }}"
    iodepth: "{{ fio_iodepth }}"
    stonewall:
