---
packages:
- fio
- tar

# A list of directories on the test host that fio jobs will be run against
fio_devices:
- /tmptest

# Where to store the fio logs on the test host we're running fio on
fio_output_dir: /tmp/fio_tests

# This relates to a directory on the host running ansible. The fio results tarball
# will be fetched and stored in this location
fio_fetch_dir: /tmp/fio_tests

fio_global_options:
  ioengine: libaio
  direct: 1
  time_based: 1
  numjobs: "{{ ansible_processor_vcpus }}"
  log_avg_msec: 5
  iodepth: 16
  size: 4g
  ramp_time: 3m
  runtime: 10m

# fio_jobs dict by blocksize
fio_jobs:
  8k:
    rw:
    - read
    - write
    - randread
    - randwrite
    stonewall:
  64k:
    rw:
    - read
    - write
    - randread
    - randwrite
    stonewall:
  1m:
    rw:
    - read
    - write
    - randread
    - randwrite
    stonewall:
